language: php

os: linux

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

branches:
  except:
    - 0.4

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: TEST_SUITE="oss"
    - php: 7.2
      env: TEST_SUITE="oss"
    - php: 7.3
      env: TEST_SUITE="oss"
    - php: 7.4
      env: TEST_SUITE="oss"

env:
  global:
    - STACK_VERSION="8.0.0-SNAPSHOT"

before_install:
  - ./travis/run_es_docker.sh

install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN} >/dev/null 2>&1; fi;
  - composer install --prefer-dist --no-interaction >/dev/null 2>&1

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - php util/RestSpecRunner.php
  - php util/EnsureClusterAlive.php

script:
  - composer run-script phpcs
  - composer run-script phpstan
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - vendor/bin/phpunit -c phpunit-integration.xml --group sync $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then php vendor/bin/coveralls; fi

notifications:
  email: true
