language: php

services:
  - docker

branches:
  except:
    - 0.4

sudo: true

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: ES_VERSION="6.7.0"

    - php: 7.1
      env: ES_VERSION="6.7.0"

    - php: 7.2
      env: ES_VERSION="6.7.0"

    - php: 7.3
      env: ES_VERSION="6.0.0"
    - php: 7.3
      env: ES_VERSION="6.1.0"
    - php: 7.3
      env: ES_VERSION="6.2.0"
    - php: 7.3
      env: ES_VERSION="6.3.0"
    - php: 7.3
      env: ES_VERSION="6.4.0"
    - php: 7.3
      env: ES_VERSION="6.5.0"
    - php: 7.3
      env: ES_VERSION="6.6.0"
    - php: 7.3
      env: ES_VERSION="6.7.0"

env:
  global:
    - ES_TEST_HOST=http://localhost:9200

before_install:
  - ./travis/run_es_docker.sh

install:
  - composer install --prefer-dist

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - php util/RestSpecRunner.php
  - php util/EnsureClusterAlive.php

script:
  - if [ $TRAVIS_PHP_VERSION != '7.3' ]; then composer run-script phpcs; fi
  - composer run-script phpstan
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - vendor/bin/phpunit -c phpunit-integration.xml --group sync $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then php vendor/bin/coveralls; fi

notifications:
  email: true
