language: php

services:
  - elasticsearch

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.6
      env: ES_VERSION="1.4.4"
    - php: 5.6
      env: ES_VERSION="1.3.9"
    - php: 5.6
      env: ES_VERSION="1.2.4"
    - php: 5.6
      env: ES_VERSION="1.1.2"
    - php: 5.6
      env: ES_VERSION="1.0.3"

env:
  global:
    - ES_VERSION="1.5.1"
    - ES_TEST_HOST=http://localhost:9200

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb

install:
  - composer install --prefer-source

before_script:
  - sleep 3 # wait till Elastic completely starts
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then php vendor/bin/coveralls; fi
